version: '3.7'

services:

  postgres:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env

  rabbitmq:
    image: rabbitmq:3.8.2-alpine
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    env_file: .env

  #redis:
  #  image: redis:5.0.6-alpine
  #  volumes:
  #    - redis_data:/data
  #  env_file: .env

  celery_worker:
    build: ./app
    command: celery worker --app=django_rest_pg.celery.app --concurrency=1 --loglevel=INFO
    volumes:
      - django_static_data:/app/static
      - django_media_data:/app/media
    env_file: .env
    depends_on:
      - rabbitmq
      - postgres

  celery_beat:
    build: ./app
    # Django Celery Beat
    command: celery beat --app=django_rest_pg.celery.app --scheduler django_celery_beat.schedulers:DatabaseScheduler --loglevel=INFO
    # Standard Celery BeatBeat
    #command: celery beat --app=django_rest_pg.celery.app --loglevel=INFO
    volumes:
      - django_static_data:/app/static
      - django_media_data:/app/media
    env_file: .env
    depends_on:
      - rabbitmq
      - postgres

  django:
    build: ./app
    command: gunicorn django_rest_pg.wsgi:application --bind 0.0.0.0:8000
    expose:
      - '8000'
    volumes:
      - django_static_data:/app/static
      - django_media_data:/app/media
    env_file: .env
    depends_on:
      - postgres
      - rabbitmq

  nginx:
    build: ./nginx
    ports:
      - '8000:80'
    volumes:
      - django_static_data:/usr/share/nginx/html/static
      - django_media_data:/usr/share/nginx/html/media
    depends_on:
      - django

volumes:

  postgres_data:
  rabbitmq_data:
  #redis_data:
  django_static_data:
  django_media_data:
