version: '3.7'

services:

  postgres:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env

  rabbitmq:
    image: rabbitmq:3.8.2-alpine
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    env_file: .env

  #redis:
  #  image: redis:5.0.6-alpine
  #  volumes:
  #    - redis_data:/data
  #  env_file: .env

  celery_worker:
    build: ./app
    command: watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery worker --app=django_rest_pg.celery.app --concurrency=1 --loglevel=INFO
    volumes:
      - ./app:/app
    env_file: .env
    depends_on:
      - rabbitmq
      - postgres

  celery_beat:
    build: ./app
    # Django Celery Beat
    command: watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery beat --app=django_rest_pg.celery.app --scheduler django_celery_beat.schedulers:DatabaseScheduler --loglevel=INFO
    # Standard Celery Beat
    #command: watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery beat --app=django_rest_pg.celery.app --loglevel=INFO
    volumes:
      - ./app:/app
    env_file: .env
    depends_on:
      - rabbitmq
      - postgres

  django:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    volumes:
      - ./app:/app
    env_file: .env
    depends_on:
      - postgres
      - rabbitmq

volumes:

  postgres_data:
  rabbitmq_data:
  #redis_data:
